package basic.database.validateUserFromDbAndPasswordFromThirdPartyService.security;
 
import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SecurityWebApplicationInitializer extends AbstractSecurityWebApplicationInitializer {
 
}